"""
This type stub file was generated by pyright.
"""

import sys

if sys.version_info[0] == 3:
    Iterable = ...
else: ...
__tracebackhide__ = ...

class HelpersMixin:
    """Helpers mixin.  For internal use only."""

    ...
